name = "brackelib"
description = "Ada library which contains various utility packages."
version = "0.0.1"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
[[depends-on]]  # Added by alr
aunit = "^21.0.0"  # Added by alr
